import os

# Get the absolute path to the directory where this config file lives
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# The name of the data file generated by your tagging app
# Users only need to change this string if they rename their CSV
DATA_SOURCE_NAME = "codebase_tags.csv"

# The full path to the data source, resolved dynamically
DATA_SOURCE = os.path.join(BASE_DIR, DATA_SOURCE_NAME)

# Words that should be excluded from the 3D topology and word frequency maps 
# because they add noise rather than semantic value.
STOP_WORDS = {
    "a", "an", "the", "in", "on", "at", "to", "for", "with", "and", "or", "of",
    "node_modules", ".git", "venv", ".venv", "__pycache__", "build",
    "dist", ".idea", "bin", "obj", ".vscode", "repo"
}
